//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLAssignment3__Client.WordGameReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameAlreadyHostedException", Namespace="http://schemas.datacontract.org/2004/07/CLAssignment3__Server")]
    [System.SerializableAttribute()]
    public partial class GameAlreadyHostedException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isGameBeingHostedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isGameBeingHosted {
            get {
                return this.isGameBeingHostedField;
            }
            set {
                if ((this.isGameBeingHostedField.Equals(value) != true)) {
                    this.isGameBeingHostedField = value;
                    this.RaisePropertyChanged("isGameBeingHosted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameBeingHostedException", Namespace="http://schemas.datacontract.org/2004/07/CLAssignment3__Server")]
    [System.SerializableAttribute()]
    public partial class GameBeingHostedException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool hostedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool hosted {
            get {
                return this.hostedField;
            }
            set {
                if ((this.hostedField.Equals(value) != true)) {
                    this.hostedField = value;
                    this.RaisePropertyChanged("hosted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://schemas.datacontract.org/2004/07/CLAssignment3__Server")]
    [System.SerializableAttribute()]
    public partial class Word : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string scrambledWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unscrambledWordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string scrambledWord {
            get {
                return this.scrambledWordField;
            }
            set {
                if ((object.ReferenceEquals(this.scrambledWordField, value) != true)) {
                    this.scrambledWordField = value;
                    this.RaisePropertyChanged("scrambledWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unscrambledWord {
            get {
                return this.unscrambledWordField;
            }
            set {
                if ((object.ReferenceEquals(this.unscrambledWordField, value) != true)) {
                    this.unscrambledWordField = value;
                    this.RaisePropertyChanged("unscrambledWord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaximumNumberOfPlayersException", Namespace="http://schemas.datacontract.org/2004/07/CLAssignment3__Server")]
    [System.SerializableAttribute()]
    public partial class MaximumNumberOfPlayersException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int playerAmmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int playerAmmount {
            get {
                return this.playerAmmountField;
            }
            set {
                if ((this.playerAmmountField.Equals(value) != true)) {
                    this.playerAmmountField = value;
                    this.RaisePropertyChanged("playerAmmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HostCantJoinException", Namespace="http://schemas.datacontract.org/2004/07/CLAssignment3__Server")]
    [System.SerializableAttribute()]
    public partial class HostCantJoinException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int playerAmmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int playerAmmount {
            get {
                return this.playerAmmountField;
            }
            set {
                if ((this.playerAmmountField.Equals(value) != true)) {
                    this.playerAmmountField = value;
                    this.RaisePropertyChanged("playerAmmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerNotPLayingTheGameException", Namespace="http://schemas.datacontract.org/2004/07/CLAssignment3__Server")]
    [System.SerializableAttribute()]
    public partial class PlayerNotPLayingTheGameException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string playerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string player {
            get {
                return this.playerField;
            }
            set {
                if ((object.ReferenceEquals(this.playerField, value) != true)) {
                    this.playerField = value;
                    this.RaisePropertyChanged("player");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordGameReference.IWordScrambleGame")]
    public interface IWordScrambleGame {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/isGameBeingHosted", ReplyAction="http://tempuri.org/IWordScrambleGame/isGameBeingHostedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CLAssignment3__Client.WordGameReference.GameAlreadyHostedException), Action="http://tempuri.org/IWordScrambleGame/isGameBeingHostedGameAlreadyHostedExceptionF" +
            "ault", Name="GameAlreadyHostedException", Namespace="http://schemas.datacontract.org/2004/07/CLAssignment3__Server")]
        bool isGameBeingHosted();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/isGameBeingHosted", ReplyAction="http://tempuri.org/IWordScrambleGame/isGameBeingHostedResponse")]
        System.Threading.Tasks.Task<bool> isGameBeingHostedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/hostGame", ReplyAction="http://tempuri.org/IWordScrambleGame/hostGameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CLAssignment3__Client.WordGameReference.GameBeingHostedException), Action="http://tempuri.org/IWordScrambleGame/hostGameGameBeingHostedExceptionFault", Name="GameBeingHostedException", Namespace="http://schemas.datacontract.org/2004/07/CLAssignment3__Server")]
        string hostGame(string userName, string hostAddress, string wordToScramble);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/hostGame", ReplyAction="http://tempuri.org/IWordScrambleGame/hostGameResponse")]
        System.Threading.Tasks.Task<string> hostGameAsync(string userName, string hostAddress, string wordToScramble);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/join", ReplyAction="http://tempuri.org/IWordScrambleGame/joinResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CLAssignment3__Client.WordGameReference.MaximumNumberOfPlayersException), Action="http://tempuri.org/IWordScrambleGame/joinMaximumNumberOfPlayersExceptionFault", Name="MaximumNumberOfPlayersException", Namespace="http://schemas.datacontract.org/2004/07/CLAssignment3__Server")]
        [System.ServiceModel.FaultContractAttribute(typeof(CLAssignment3__Client.WordGameReference.HostCantJoinException), Action="http://tempuri.org/IWordScrambleGame/joinHostCantJoinExceptionFault", Name="HostCantJoinException", Namespace="http://schemas.datacontract.org/2004/07/CLAssignment3__Server")]
        CLAssignment3__Client.WordGameReference.Word join(string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/join", ReplyAction="http://tempuri.org/IWordScrambleGame/joinResponse")]
        System.Threading.Tasks.Task<CLAssignment3__Client.WordGameReference.Word> joinAsync(string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/guessWord", ReplyAction="http://tempuri.org/IWordScrambleGame/guessWordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CLAssignment3__Client.WordGameReference.PlayerNotPLayingTheGameException), Action="http://tempuri.org/IWordScrambleGame/guessWordPlayerNotPLayingTheGameExceptionFau" +
            "lt", Name="PlayerNotPLayingTheGameException", Namespace="http://schemas.datacontract.org/2004/07/CLAssignment3__Server")]
        bool guessWord(string playerName, string guessedWord, string unscrambledWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleGame/guessWord", ReplyAction="http://tempuri.org/IWordScrambleGame/guessWordResponse")]
        System.Threading.Tasks.Task<bool> guessWordAsync(string playerName, string guessedWord, string unscrambledWord);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordScrambleGameChannel : CLAssignment3__Client.WordGameReference.IWordScrambleGame, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordScrambleGameClient : System.ServiceModel.ClientBase<CLAssignment3__Client.WordGameReference.IWordScrambleGame>, CLAssignment3__Client.WordGameReference.IWordScrambleGame {
        
        public WordScrambleGameClient() {
        }
        
        public WordScrambleGameClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordScrambleGameClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordScrambleGameClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordScrambleGameClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool isGameBeingHosted() {
            return base.Channel.isGameBeingHosted();
        }
        
        public System.Threading.Tasks.Task<bool> isGameBeingHostedAsync() {
            return base.Channel.isGameBeingHostedAsync();
        }
        
        public string hostGame(string userName, string hostAddress, string wordToScramble) {
            return base.Channel.hostGame(userName, hostAddress, wordToScramble);
        }
        
        public System.Threading.Tasks.Task<string> hostGameAsync(string userName, string hostAddress, string wordToScramble) {
            return base.Channel.hostGameAsync(userName, hostAddress, wordToScramble);
        }
        
        public CLAssignment3__Client.WordGameReference.Word join(string playerName) {
            return base.Channel.join(playerName);
        }
        
        public System.Threading.Tasks.Task<CLAssignment3__Client.WordGameReference.Word> joinAsync(string playerName) {
            return base.Channel.joinAsync(playerName);
        }
        
        public bool guessWord(string playerName, string guessedWord, string unscrambledWord) {
            return base.Channel.guessWord(playerName, guessedWord, unscrambledWord);
        }
        
        public System.Threading.Tasks.Task<bool> guessWordAsync(string playerName, string guessedWord, string unscrambledWord) {
            return base.Channel.guessWordAsync(playerName, guessedWord, unscrambledWord);
        }
    }
}
